Signup form
alexatrifilio/films-films-films pull request #2
Opened 2022-09-15 01:15 UTC by alexatrifilio

2022-09-15 22:03 UTC, adrianmdp requested changes

2022-09-15 22:03 UTC, adrianmdp commented on src/pages/SignUp/Form/index.tsx
> +        <label htmlFor="countries"> País </label>
y el register?

2022-09-15 22:03 UTC, adrianmdp commented on src/pages/SignUp/Form/index.tsx
> +        <select name="cities" id="cities">
y el register?

2022-09-16 14:50 UTC, alexatrifilio commented on src/pages/SignUp/Form/index.tsx
> +        <select name="cities" id="cities">
me los olvidé (: jejeje

2022-09-17 00:46 UTC, adrianmdp requested changes

2022-09-17 00:46 UTC, adrianmdp commented on src/pages/SignUp/Form/index.tsx
> +          onChange={(e) => {
No necesitas el onchange cuando usas react-hooks-form. Estoy viendo que al siguiente se lo quitaste asi que este puede que se te haya pasado. 
El state lo maneja directamente React Hook Form

2022-09-17 00:46 UTC, adrianmdp commented on src/pages/SignUp/Form/index.tsx
> +  const [selectCountry, setSelectCountry] = useState<Country>({
Estoy lo vamos a tener que ver juntos xq la libreria React Hook Form te permite saber que elemento siene seleccionado alguno de los controles con tienen el register.
Mirate la funcion watch de la libreria.

2022-09-18 16:42 UTC, adrianmdp approved these changes

2022-09-18 16:42 UTC, adrianmdp commented on src/pages/SignUp/Form/index.tsx
> +          <option disabled>Seleccione su país</option>
A los select agregales el selected también así inician seleccionados.

2022-09-18 19:31 UTC, merged